//This is a temporary file generated by spyglass Lib2V utility from the library
//<USERLIB_ss_0p90v_0p90v_m40c.lib>. Do not modify this or use this.
//spyglass xref filename </home/users/team3_03/Desktop/design2021/spyglass/./spyglass-1/soctop/Design_Read/spyglass_spysch/spyglass/mem256x32_ss_0p90v_0p90v_m40c_0.v>
//spyglass xref version SpyGlass_vQ-2020.03-SP2-6

//spyglass xref lineno 306, -1
`celldefine
module mem256x32 (Q, WEN, A, D, EMA, EMAW, CLK, CEN, GWEN, RET1N);
    output [31:0]Q;
    input  [31:0]WEN;
    input  [7:0]A;
    input  [31:0]D;
    input  [2:0]EMA;
    input  [1:0]EMAW;
    input  CLK;
    input  CEN;
    input  GWEN;
    input  RET1N;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine
